import React from "react";
import * as _Builtin from "./_Builtin";
import * as _utils from "./utils";
import _styles from "./InterviewPrepHome.module.css";

export function InterviewPrepHome({
  as: _Component = _Builtin.Block,
  onClickMockTest = {},
  onClickCaq = {},
  slotAll,
  slotComplete,
  slotIncomplete,
  skeletonVisibility = true,
  isInterviewHistoryVisible = true,
}) {
  return (
    <_Component className={_utils.cx(_styles, "interview-component")} tag="div">
      <_Builtin.Block
        className={_utils.cx(_styles, "container-1280")}
        tag="div"
      >
        <_Builtin.Block
          className={_utils.cx(_styles, "interview-wrapper")}
          tag="div"
        >
          <_Builtin.Block
            className={_utils.cx(_styles, "interview-image-wrapper")}
            id={_utils.cx(
              _styles,
              "w-node-_9b9ef5ce-1976-bcae-864c-5450e3dcb1d3-e3dcb1d1"
            )}
            tag="div"
          >
            <_Builtin.Image
              className={_utils.cx(_styles, "interview-image")}
              loading="lazy"
              width="auto"
              height="auto"
              src="https://uploads-ssl.webflow.com/647ff5fb374a40bef3d73aed/64847176a7baf73f869bfde8_Frame%2043.png"
            />
          </_Builtin.Block>
          <_Builtin.Block
            className={_utils.cx(_styles, "interview-right-content-wrapper")}
            id={_utils.cx(
              _styles,
              "w-node-_9b9ef5ce-1976-bcae-864c-5450e3dcb1d5-e3dcb1d1"
            )}
            tag="div"
          >
            <_Builtin.Block
              className={_utils.cx(_styles, "welcome-module-wrapper")}
              tag="div"
            >
              <_Builtin.Heading tag="h2">
                {"Welcome to the module"}
              </_Builtin.Heading>
              <_Builtin.Paragraph
                className={_utils.cx(_styles, "text-grey-600")}
              >
                {"Forem ipsum dolor sit amet, consectetur adipiscing elit."}
              </_Builtin.Paragraph>
              <_Builtin.Block
                className={_utils.cx(_styles, "interview-cards-wrapper")}
                tag="div"
              >
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "interview-cards-item",
                    "bg-kale-200"
                  )}
                  tag="div"
                  {...onClickMockTest}
                >
                  <_Builtin.Block
                    className={_utils.cx(_styles, "interview-top-content")}
                    tag="div"
                  >
                    <_Builtin.Image
                      loading="lazy"
                      width="auto"
                      height="auto"
                      src="https://uploads-ssl.webflow.com/647ff5fb374a40bef3d73aed/64820ff84e6c35a26e842acf_glitter.svg"
                    />
                    <_Builtin.Block
                      className={_utils.cx(_styles, "arrow-wrapper")}
                      tag="div"
                    >
                      <_Builtin.Image
                        loading="lazy"
                        width="auto"
                        height="auto"
                        src="https://uploads-ssl.webflow.com/647ff5fb374a40bef3d73aed/64820ff84e6c35a26e842ad0_Chevron%20left%20-%2012px%20icon.svg"
                      />
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(_styles, "interview-bottom-content")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(_styles, "interview-title")}
                      tag="div"
                    >
                      {"AI powered mock Test"}
                    </_Builtin.Block>
                    <_Builtin.Paragraph
                      className={_utils.cx(_styles, "text-kale-500")}
                    >
                      {
                        "Torem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis."
                      }
                    </_Builtin.Paragraph>
                  </_Builtin.Block>
                </_Builtin.Block>
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "interview-cards-item",
                    "bg-blue-200"
                  )}
                  tag="div"
                  {...onClickCaq}
                >
                  <_Builtin.Block
                    className={_utils.cx(_styles, "interview-top-content")}
                    tag="div"
                  >
                    <_Builtin.Image
                      loading="lazy"
                      width="auto"
                      height="auto"
                      src="https://uploads-ssl.webflow.com/647ff5fb374a40bef3d73aed/64820ff84e6c35a26e842ace_Rearrange%20-%2016px%20icon.svg"
                    />
                    <_Builtin.Block
                      className={_utils.cx(_styles, "arrow-wrapper")}
                      tag="div"
                    >
                      <_Builtin.Image
                        loading="lazy"
                        width="auto"
                        height="auto"
                        src="https://uploads-ssl.webflow.com/647ff5fb374a40bef3d73aed/64820ff84e6c35a26e842ad0_Chevron%20left%20-%2012px%20icon.svg"
                      />
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(_styles, "interview-bottom-content")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(_styles, "interview-title")}
                      tag="div"
                    >
                      {"Commonly asked questions"}
                    </_Builtin.Block>
                    <_Builtin.Paragraph
                      className={_utils.cx(_styles, "text-grey-600")}
                    >
                      {
                        "Vorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis."
                      }
                    </_Builtin.Paragraph>
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.Block>
              {isInterviewHistoryVisible ? (
                <_Builtin.Block
                  className={_utils.cx(_styles, "interview-history")}
                  tag="div"
                >
                  <_Builtin.Block
                    className={_utils.cx(_styles, "history-heading")}
                    tag="div"
                  >
                    <_Builtin.Image
                      loading="lazy"
                      width="auto"
                      height="auto"
                      src="https://uploads-ssl.webflow.com/647ff5fb374a40bef3d73aed/6482c57b2de566c5d90ed80f_history.svg"
                    />
                    <_Builtin.Block
                      className={_utils.cx(_styles, "text-lg-bold")}
                      tag="div"
                    >
                      {"Interviews History"}
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.TabsWrapper
                    className={_utils.cx(_styles, "tabs", "interview")}
                    current="Tab 1"
                    easing="ease"
                    fadeIn={300}
                    fadeOut={100}
                  >
                    <_Builtin.TabsMenu
                      className={_utils.cx(_styles, "tabs-menu")}
                      tag="div"
                    >
                      <_Builtin.TabsLink
                        className={_utils.cx(_styles, "tablink", "is-small")}
                        data-w-tab="Tab 1"
                      >
                        <_Builtin.Block tag="div">{"All"}</_Builtin.Block>
                      </_Builtin.TabsLink>
                      <_Builtin.TabsLink
                        className={_utils.cx(_styles, "tablink", "is-small")}
                        data-w-tab="Tab 2"
                      >
                        <_Builtin.Block tag="div">{"Complete"}</_Builtin.Block>
                      </_Builtin.TabsLink>
                      <_Builtin.TabsLink
                        className={_utils.cx(_styles, "tablink", "is-small")}
                        data-w-tab="Tab 3"
                      >
                        <_Builtin.Block tag="div">
                          {"In Complete"}
                        </_Builtin.Block>
                      </_Builtin.TabsLink>
                    </_Builtin.TabsMenu>
                    <_Builtin.TabsContent tag="div">
                      <_Builtin.TabsPane tag="div" data-w-tab="Tab 1">
                        <_Builtin.Block tag="div">
                          <_Builtin.Block
                            className={_utils.cx(_styles, "slot-previous")}
                            tag="div"
                          >
                            {slotAll}
                          </_Builtin.Block>
                          {skeletonVisibility ? (
                            <_Builtin.Block
                              className={_utils.cx(_styles, "stack-column")}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                          ) : null}
                        </_Builtin.Block>
                      </_Builtin.TabsPane>
                      <_Builtin.TabsPane tag="div" data-w-tab="Tab 2">
                        <_Builtin.Block tag="div">
                          <_Builtin.Block
                            className={_utils.cx(_styles, "slot-previous")}
                            tag="div"
                          >
                            {slotComplete}
                          </_Builtin.Block>
                          {skeletonVisibility ? (
                            <_Builtin.Block
                              className={_utils.cx(_styles, "stack-column")}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                          ) : null}
                        </_Builtin.Block>
                      </_Builtin.TabsPane>
                      <_Builtin.TabsPane tag="div" data-w-tab="Tab 3">
                        <_Builtin.Block tag="div">
                          <_Builtin.Block
                            className={_utils.cx(_styles, "slot-previous")}
                            tag="div"
                          >
                            {slotIncomplete}
                          </_Builtin.Block>
                          {skeletonVisibility ? (
                            <_Builtin.Block
                              className={_utils.cx(_styles, "stack-column")}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "past-interview",
                                  "skeleton"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "past-interview-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-lg-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Job Title"}
                                  </_Builtin.Block>
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "past-interview-company-wrap",
                                      "div-block-4",
                                      "div-block-5"
                                    )}
                                    tag="div"
                                  >
                                    <_Builtin.Image
                                      className={_utils.cx(
                                        _styles,
                                        "interview-compant-icon"
                                      )}
                                      width="auto"
                                      height="auto"
                                      loading="lazy"
                                      src="https://d3e54v103j8qbb.cloudfront.net/plugins/Basic/assets/placeholder.60f9b1840c.svg"
                                    />
                                    <_Builtin.Block
                                      className={_utils.cx(
                                        _styles,
                                        "text-md-skeleton"
                                      )}
                                      tag="div"
                                    >
                                      {"This is text"}
                                    </_Builtin.Block>
                                  </_Builtin.Block>
                                </_Builtin.Block>
                                <_Builtin.Block
                                  className={_utils.cx(
                                    _styles,
                                    "interview-badge-wrap"
                                  )}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "status-badge-skeleton"
                                    )}
                                    tag="div"
                                  >
                                    {"Incomplete"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                          ) : null}
                        </_Builtin.Block>
                      </_Builtin.TabsPane>
                    </_Builtin.TabsContent>
                  </_Builtin.TabsWrapper>
                </_Builtin.Block>
              ) : null}
            </_Builtin.Block>
          </_Builtin.Block>
        </_Builtin.Block>
      </_Builtin.Block>
    </_Component>
  );
}
